version: '3'

services:
  postgres_dev:
    container_name: "news_api_dev"
    restart: always
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker-data/db-data:/var/lib/posgresql/data

  db_manager:
    image: adminer
    depends_on:
      - postgres_dev
    container_name: "db_manager"
    resart: always
    ports: 8080:8080


# postgres_test:
#   container_name: "news_api_test"
#   image: "postgres:latest"
#   ports:
#     - "5432:5432"
#   environment:
#     POSTGRES_USER: ${POSTGRES_USER_TEST}
#     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
#     POSTGRES_DB: ${POSTGRES_DB_TEST}

