version: '3'
services:

  postgres_dev:
    container_name: "news_api_dev"
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}


  postgres_test:
    container_name: "news_api_test"
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      POSTGRES_DB: ${POSTGRES_DB_TEST}

